# new container based environment
sudo: false

cache:
  pip: true

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install -r requirements.txt"
script:
  - "python setup.py build_ext --inplace"
  - "flake8 src tests"
  - "python setup.py test"
